"""empty message

Revision ID: 2cf77aa38dfe
Revises: 54430c3f1997
Create Date: 2020-08-31 11:57:43.650912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf77aa38dfe'
down_revision = '54430c3f1997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'client_id')
    # ### end Alembic commands ###
